disabled_rules:
    - line_length
    - type_body_length

function_body_length:
    - 200 # warning
    - 300 # error

opt_in_rules:
  - vertical_whitespace_opening_braces



type_name:
    min_length: 3
    max_length:
        warning: 50
        error: 60
    excluded: T # excluded via string

statement_position:
    statement_mode: uncuddled_else

excluded:
    - Pods
    - Carthage


